[debug]
DEBUG = 1

[network]
IP = '127.0.0.1'
OUT_PORT = 47000

[address]
    ADDRESS = [
        '/button_0',
        '/button_1',
        '/button_2',
        '/button_3',
        '/pot_0',
        '/pot_1',
        '/pot_2',
        '/pot_3'
    ]